# risk detector placeholder
"""
Risk event detector.

Reads the scene graph and identifies potentially dangerous
object relationships.
"""

from .risk_rules import get_risk_rule


class RiskDetector:

    def __init__(self, min_confidence=0.40):
        self.min_confidence = min_confidence

    def detect(self, scene_graph):
        """
        Detect potential risk events from a scene graph.

        Parameters
        ----------
        scene_graph : dict
            Scene graph containing nodes and edges.

        Returns
        -------
        list
            List of detected risk events.
        """

        nodes = scene_graph.get("nodes", [])
        edges = scene_graph.get("edges", [])

        # -----------------------------------------------------
        # Keep only sufficiently confident detections
        # -----------------------------------------------------
        valid_nodes = {
            node["id"]: node
            for node in nodes
            if node.get("confidence", 0.0) >= self.min_confidence
        }

        risk_events = []

        # -----------------------------------------------------
        # Analyze relationships
        # -----------------------------------------------------
        for edge in edges:

            source_id = edge.get("source")
            target_id = edge.get("target")
            relation = edge.get("relation")

            if source_id not in valid_nodes:
                continue

            if target_id not in valid_nodes:
                continue

            source = valid_nodes[source_id]
            target = valid_nodes[target_id]

            class_a = source.get("class_name")
            class_b = target.get("class_name")

            rule = get_risk_rule(
                class_a,
                class_b,
                relation
            )

            if rule is None:
                continue

            event = {
                "risk_type": rule["risk_type"],
                "severity": rule["severity"],
                "score": rule["score"],
                "reason": rule["reason"],
                "relation": relation,
                "objects": [
                    {
                        "id": source_id,
                        "class_name": class_a,
                        "confidence": source.get("confidence", 0.0),
                    },
                    {
                        "id": target_id,
                        "class_name": class_b,
                        "confidence": target.get("confidence", 0.0),
                    },
                ],
            }

            risk_events.append(event)

        return self._remove_duplicates(risk_events)

    @staticmethod
    def _remove_duplicates(events):
        """
        Remove duplicate risk events generated by symmetric
        relationships.
        """

        unique_events = []
        seen = set()

        for event in events:

            object_ids = tuple(
                sorted(
                    obj["id"]
                    for obj in event["objects"]
                )
            )

            key = (
                event["risk_type"],
                object_ids,
            )

            if key in seen:
                continue

            seen.add(key)
            unique_events.append(event)

        return unique_events